Feature/admin dashboard
Lambda-School-Labs/Labs27-A-Ecosoap-FE pull request #2
Opened 2020-10-06 23:36 UTC by Istott

Created dashboard component with GET request endpoint with mock data. Added search bar and drop down option selector for orders. Added less file for dashboard index styling.

2020-10-07 16:37 UTC, wSedlacek requested changes
We are lacking some test that will be required to merge and one test has broken. Please fix these test before merging.

I also had a few questions on the code. Please reply to these before requesting rereview.

2020-10-07 16:37 UTC, wSedlacek commented on CODE_OF_CONDUCT.md
> +  professional setting
Let's revert this file and make a separate PR to format any files

2020-10-07 16:37 UTC, wSedlacek commented on src/components/common/Header.js
> +}
This doesn't appear to be used anywhere?
Is this for future development or is this simply zombie code?

2020-10-07 16:37 UTC, wSedlacek commented on src/components/common/Order.js
> +    <>
Should this be a `<div>` or some other element rather then a fragment so that these are grouped together on the DOM?
Would we need to apply a class or id etc here in the future?

2020-10-07 16:37 UTC, wSedlacek commented on src/components/common/Order.js
> +      <h4>Status:</h4>
I noticed that we have `<h4>`, but the place where this is used previously uses an `<h1>` so what happened to `<h2>` and `<h3>`? 

Remember [Avoid skipping heading levels: always start from h1, next use h2 and so on.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Usage_notes)

2020-10-07 16:37 UTC, wSedlacek commented on src/components/common/Order.js
> +          <h4>Comments:</h4>
Should this header be above all the comments instead of for each comment?

2020-10-07 16:37 UTC, wSedlacek commented on src/components/common/TopHeader.js
> +    event.preventDefault();
Is `preventDefault()` necessary here?

2020-10-07 16:37 UTC, wSedlacek commented on src/components/pages/Dashboard/dashboard.less
> +    }
Is there a reason `.searchBar` should be nested? Does the fact that is is in `.dashboard` affect the reason as to why these styles would be applied?

2020-10-07 16:37 UTC, wSedlacek commented on src/components/pages/Dashboard/index.js
> +  const { Panel } = Collapse;
What was happening when this was outside of the component ie on line 10 or above?
Did we have errors?

2020-10-07 23:14 UTC, hera commented on CODE_OF_CONDUCT.md
> +  professional setting
Changed it to its original version

2020-10-07 23:15 UTC, hera commented on src/components/common/Header.js
> +}
Zombie! Deleted the file

2020-10-07 23:16 UTC, hera commented on src/components/common/Order.js
> +    <>
Changed to div

2020-10-07 23:16 UTC, hera commented on src/components/common/Order.js
> +      <h4>Status:</h4>
Changed h4 to h2

2020-10-07 23:17 UTC, hera commented on src/components/common/TopHeader.js
> +    event.preventDefault();
Removed the line with preventDefault

2020-10-07 23:18 UTC, hera commented on src/components/pages/Dashboard/dashboard.less
> +    }
Moved .searchBar to the same level

2020-10-07 23:19 UTC, hera commented on src/components/pages/Dashboard/dashboard.less
> +    }
Test

2020-10-08 16:05 UTC, wSedlacek commented
We also do need the test to merge this PR. So make sure to get those done.

2020-10-08 16:11 UTC, wSedlacek commented on src/components/common/TopHeader.js
> +  const { Header } = Layout;
Can we also move this out of the component?

2020-10-08 17:36 UTC, wSedlacek approved these changes
Awesome work Alex and Issac!

2020-10-08 17:36 UTC, merged